<a href="https://colab.research.google.com/github/MISJasonChuang/drift_detection/blob/main/drift_detect.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install -U Cython
!pip install -U scikit-multiflow

Requirement already satisfied: Cython in /usr/local/lib/python3.10/dist-packages (0.29.36)
Collecting Cython
  Downloading Cython-3.0.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 14.6 MB/s eta 0:00:00
Installing collected packages: Cython
  Attempting uninstall: Cython
    Found existing installation: Cython 0.29.36
    Uninstalling Cython-0.29.36:
      Successfully uninstalled Cython-0.29.36
Successfully installed Cython-3.0.1
Collecting scikit-multiflow
  Downloading scikit-multiflow-0.5.3.tar.gz (450 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 450.6/450.6 kB 5.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: sortedcontainers>=1.5.7 in /usr/local/lib/python3.10/dist-packages (from scikit-multiflow) (2.4.0)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.10/dist-packages (from scikit-multiflow) (1.23.5)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-multiflow) (1.10.1)
Requirement already satisfied: matplotlib>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-multiflow) (3.7.1)
Requirement already satisfied: scikit-learn>=0.20 in /usr/local/lib/python3.10/dist-packages (from scikit-multiflow) (1.2.2)
Requirement already satisfied: pandas>=0.25.3 in /usr/local/lib/python3.10/dist-packages (from scikit-multiflow) (1.5.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=2.0.0->scikit-multiflow) (1.1.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=2.0.0->scikit-multiflow) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=2.0.0->scikit-multiflow) (4.42.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=2.0.0->scikit-multiflow) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=2.0.0->scikit-multiflow) (23.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=2.0.0->scikit-multiflow) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=2.0.0->scikit-multiflow) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=2.0.0->scikit-multiflow) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.25.3->scikit-multiflow) (2023.3)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20->scikit-multiflow) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20->scikit-multiflow) (3.2.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib>=2.0.0->scikit-multiflow) (1.16.0)
Building wheels for collected packages: scikit-multiflow
  Building wheel for scikit-multiflow (setup.py) ... done
  Created wheel for scikit-multiflow: filename=scikit_multiflow-0.5.3-cp310-cp310-linux_x86_64.whl size=1254673 sha256=f46a5411dda33e83ee892cdf33faf8c9e0004b59c432fa49104299ddb79caa12
  Stored in directory: /root/.cache/pip/wheels/6e/1b/56/45b17a6cf203d98000a45976cb0dd0c4c3f11960e6a505f231
Successfully built scikit-multiflow
Installing collected packages: scikit-multiflow
Successfully installed scikit-multiflow-0.5.3

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
import pandas as pd
import numpy as np
from skmultiflow.drift_detection.adwin import ADWIN
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Gold_Prices.csv')
df

,Name,US dollar,Euro,Japanese yen,Pound sterling,Canadian dollar,Swiss franc,Indian rupee,Chinese renmimbi,US dollar.1,...,Vietnamese dong,Egyptian pound,Korean won,Euro.1,Russian ruble,US dollar.2,South African rand,Chinese renmimbi.1,Canadian dollar.1,Australian dollar
0,1978/12/29,226.0,137.1,NaN,110.7,NaN,NaN,NaN,NaN,226.0,...,NaN,NaN,NaN,137.1,NaN,226.0,NaN,NaN,NaN,NaN
1,1979/1/1,226.0,137.1,NaN,110.7,NaN,NaN,NaN,NaN,226.0,...,NaN,NaN,NaN,137.1,NaN,226.0,NaN,NaN,NaN,NaN
2,1979/1/2,226.8,137.3,43164.9,111.5,263.7,359.6,1792.9,NaN,226.8,...,NaN,NaN,107470.0,137.3,NaN,226.8,194.6,NaN,263.7,193.6
3,1979/1/3,218.6,134.0,43717.9,108.0,264.4,365.9,1802.2,NaN,218.6,...,NaN,NaN,108027.4,134.0,NaN,218.6,192.2,NaN,264.4,193.0
4,1979/1/4,223.2,136.8,43674.9,110.7,264.1,366.4,1811.7,NaN,223.2,...,NaN,NaN,108602.5,136.8,NaN,223.2,193.0,NaN,264.1,194.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10896,2020/10/5,1909.6,1619.3,201739.7,1471.4,2533.1,1747.1,139954.6,13005.5,1909.6,...,44310360.7,30057.1,2221724.1,1619.3,149390.4,1909.6,31453.5,13005.5,2533.1,2655.7
10897,2020/10/6,1913.4,1622.7,202083.7,1475.0,2537.9,1749.0,140560.7,13031.4,1913.4,...,44405228.2,30088.2,2221457.3,1622.7,149144.9,1913.4,31570.0,13031.4,2537.9,2671.4
10898,2020/10/7,1884.5,1602.3,199804.1,1461.0,2503.7,1728.2,138176.2,12834.6,1884.5,...,43730764.8,29551.3,2182533.5,1602.3,147410.3,1884.5,31373.4,12834.6,2503.7,2640.1
10899,2020/10/8,1887.5,1606.5,200116.9,1459.9,2496.1,1732.2,138241.5,12854.7,1887.5,...,43773739.3,29651.8,2176701.7,1606.5,146305.7,1887.5,31298.7,12854.7,2496.1,2637.0
10900,2020/10/9,1923.3,1627.9,203201.0,1479.7,2526.1,1753.4,140676.1,12912.1,1923.3,...,44605937.3,30214.3,2217988.1,1627.9,147532.5,1923.3,31601.4,12912.1,2526.1,2661.0

In [ ]:
us = df[["US dollar"]]
print(us.isnull().sum())
us = us.to_numpy()
us

US dollar    0
dtype: int64

array([[ 226. ],
       [ 226. ],
       [ 226.8],
       ...,
       [1884.5],
       [1887.5],
       [1923.3]])

In [ ]:
adwin = ADWIN(delta=0.002)
# Adding stream elements to ADWIN and verifying if drift occurred
count = 0
for i in range(len(us)):
    adwin.add_element(us[i][0])
    if adwin.detected_change():
        count+=1
        print('Change detected in data: ' + str(us[i][0]) + ' - at index: ' + str(i))
print("count ",count)

Change detected in data: [244.4] - at index: 63
Change detected in data: [281.5] - at index: 127
Change detected in data: [380.4] - at index: 191
Change detected in data: [395.] - at index: 223
Change detected in data: [473.1] - at index: 255
Change detected in data: [682.] - at index: 287
Change detected in data: [561.] - at index: 319
Change detected in data: [512.5] - at index: 351
Change detected in data: [602.5] - at index: 383
Change detected in data: [622.] - at index: 415
Change detected in data: [668.] - at index: 447
Change detected in data: [642.5] - at index: 479
Change detected in data: [523.5] - at index: 543
Change detected in data: [492.] - at index: 575
Change detected in data: [482.8] - at index: 607
Change detected in data: [464.3] - at index: 639
Change detected in data: [408.8] - at index: 671
Change detected in data: [436.8] - at index: 703
Change detected in data: [415.3] - at index: 767
Change detected in data: [330.5] - at index: 831
Change detected in data: [346.8] - at index: 863
Change detected in data: [318.8] - at index: 895
Change detected in data: [347.8] - at index: 927
Change detected in data: [428.3] - at index: 991
Change detected in data: [440.3] - at index: 1023
Change detected in data: [414.] - at index: 1087
Change detected in data: [417.] - at index: 1215
Change detected in data: [365.3] - at index: 1311
Change detected in data: [380.3] - at index: 1375
Change detected in data: [364.8] - at index: 1439
Change detected in data: [349.3] - at index: 1471
Change detected in data: [345.] - at index: 1535
Change detected in data: [308.3] - at index: 1567
Change detected in data: [304.2] - at index: 1599
Change detected in data: [321.1] - at index: 1631
Change detected in data: [322.8] - at index: 1663
Change detected in data: [317.8] - at index: 1695
Change detected in data: [351.8] - at index: 1887
Change detected in data: [345.3] - at index: 1919
Change detected in data: [362.4] - at index: 1983
Change detected in data: [430.] - at index: 2015
Change detected in data: [408.] - at index: 2047
Change detected in data: [390.8] - at index: 2079
Change detected in data: [456.8] - at index: 2175
Change detected in data: [457.2] - at index: 2239
Change detected in data: [493.5] - at index: 2335
Change detected in data: [428.5] - at index: 2527
Change detected in data: [402.5] - at index: 2623
Change detected in data: [386.4] - at index: 2655
Change detected in data: [384.] - at index: 2687
Change detected in data: [370.6] - at index: 2751
Change detected in data: [361.4] - at index: 2783
Change detected in data: [411.3] - at index: 2911
Change detected in data: [390.8] - at index: 3071
Change detected in data: [357.8] - at index: 3295
Change detected in data: [354.] - at index: 3327
Change detected in data: [355.9] - at index: 3359
Change detected in data: [343.4] - at index: 3519
Change detected in data: [348.3] - at index: 3583
Change detected in data: [332.6] - at index: 3711
Change detected in data: [352.8] - at index: 3839
Change detected in data: [363.3] - at index: 3871
Change detected in data: [385.6] - at index: 3903
Change detected in data: [388.6] - at index: 4063
Change detected in data: [390.8] - at index: 4095
Change detected in data: [390.4] - at index: 4255
Change detected in data: [349.1] - at index: 4767
Change detected in data: [342.8] - at index: 4799
Change detected in data: [318.] - at index: 4831
Change detected in data: [322.1] - at index: 4863
Change detected in data: [331.7] - at index: 4895
Change detected in data: [304.1] - at index: 4927
Change detected in data: [290.2] - at index: 4959
Change detected in data: [298.2] - at index: 4991
Change detected in data: [300.9] - at index: 5055
Change detected in data: [296.3] - at index: 5087
Change detected in data: [283.4] - at index: 5279
Change detected in data: [258.9] - at index: 5407
Change detected in data: [283.9] - at index: 5535
Change detected in data: [275.5] - at index: 5567
Change detected in data: [263.8] - at index: 5695
Change detected in data: [268.8] - at index: 5887
Change detected in data: [326.6] - at index: 6111
Change detected in data: [316.2] - at index: 6143
Change detected in data: [312.8] - at index: 6175
Change detected in data: [316.2] - at index: 6207
Change detected in data: [352.6] - at index: 6271
Change detected in data: [351.9] - at index: 6303
Change detected in data: [324.8] - at index: 6335
Change detected in data: [371.4] - at index: 6367
Change detected in data: [343.4] - at index: 6399
Change detected in data: [358.8] - at index: 6431
Change detected in data: [424.4] - at index: 6527
Change detected in data: [417.7] - at index: 6591
Change detected in data: [415.7] - at index: 6719
Change detected in data: [426.1] - at index: 6847
Change detected in data: [424.3] - at index: 6879
Change detected in data: [569.8] - at index: 7071
Change detected in data: [550.8] - at index: 7103
Change detected in data: [678.] - at index: 7135
Change detected in data: [567.] - at index: 7167
Change detected in data: [644.4] - at index: 7199
Change detected in data: [580.5] - at index: 7231
Change detected in data: [647.7] - at index: 7423
Change detected in data: [704.2] - at index: 7487
Change detected in data: [767.5] - at index: 7519
Change detected in data: [809.5] - at index: 7551
Change detected in data: [888.3] - at index: 7583
Change detected in data: [972.5] - at index: 7615
Change detected in data: [918.] - at index: 7647
Change detected in data: [803.5] - at index: 7743
Change detected in data: [780.] - at index: 7807
Change detected in data: [891.] - at index: 7903
Change detected in data: [975.5] - at index: 7935
Change detected in data: [1058.8] - at index: 8031
Change detected in data: [1126.8] - at index: 8095
Change detected in data: [1107.] - at index: 8127
Change detected in data: [1193.3] - at index: 8223
Change detected in data: [1223.5] - at index: 8255
Change detected in data: [1405.5] - at index: 8351
Change detected in data: [1371.3] - at index: 8383
Change detected in data: [1505.5] - at index: 8479
Change detected in data: [1739.] - at index: 8511
Change detected in data: [1643.] - at index: 8543
Change detected in data: [1773.] - at index: 8575
Change detected in data: [1748.] - at index: 8639
Change detected in data: [1611.] - at index: 8767
Change detected in data: [1683.5] - at index: 8831
Change detected in data: [1665.] - at index: 8863
Change detected in data: [1610.8] - at index: 8927
Change detected in data: [1469.3] - at index: 8959
Change detected in data: [1384.8] - at index: 8991
Change detected in data: [1314.5] - at index: 9023
Change detected in data: [1349.3] - at index: 9087
Change detected in data: [1225.3] - at index: 9119
Change detected in data: [1260.5] - at index: 9151
Change detected in data: [1292.8] - at index: 9279
Change detected in data: [1194.] - at index: 9375
Change detected in data: [1288.8] - at index: 9407
Change detected in data: [1196.5] - at index: 9471
Change detected in data: [1184.3] - at index: 9599
Change detected in data: [1088.2] - at index: 9663
Change detected in data: [1223.9] - at index: 9759
Change detected in data: [1357.1] - at index: 9791
Change detected in data: [1327.3] - at index: 9823
Change detected in data: [1245.8] - at index: 9983
Change detected in data: [1252.] - at index: 10015
Change detected in data: [1285.2] - at index: 10079
Change detected in data: [1291.] - at index: 10175
Change detected in data: [1323.9] - at index: 10239
Change detected in data: [1224.2] - at index: 10399
Change detected in data: [1258.2] - at index: 10431
Change detected in data: [1379.5] - at index: 10559
Change detected in data: [1465.3] - at index: 10591
Change detected in data: [1503.5] - at index: 10623
Change detected in data: [1508.8] - at index: 10655
Change detected in data: [1487.7] - at index: 10751
Change detected in data: [1703.4] - at index: 10783
Change detected in data: [1733.5] - at index: 10815
Change detected in data: [1940.9] - at index: 10847
Change detected in data: [1966.3] - at index: 10879
count  161

In [6]:
df2 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/gold prices 2000-2023.csv')
df2

            Date   Close    Volume    Open    High     Low
0     2000-01-04   283.7   21621.0   289.5   289.5   280.0
1     2000-01-05   282.1   25448.0   283.7   285.0   281.0
2     2000-01-06   282.4   19055.0   281.6   282.8   280.2
3     2000-01-07   282.9   11266.0   282.5   284.5   282.0
4     2000-01-10   282.7   30603.0   282.4   283.9   281.8
...          ...     ...       ...     ...     ...     ...
6000  2023-08-11  1946.6  119090.0  1944.9  1953.6  1942.7
6001  2023-08-14  1944.0  117514.0  1945.6  1948.2  1934.2
6002  2023-08-15  1935.2  161512.0  1939.4  1944.3  1927.5
6003  2023-08-16  1928.3  124766.0  1933.1  1938.2  1922.0
6004  2023-08-17  1915.2  146770.0  1922.4  1933.5  1914.2

[6005 rows x 6 columns]

In [7]:
close = df2[["Close"]]
print(close.isnull().sum())
close = close.to_numpy()
close

Close    0
dtype: int64

array([[ 283.7],
       [ 282.1],
       [ 282.4],
       ...,
       [1935.2],
       [1928.3],
       [1915.2]])

In [8]:
adwin = ADWIN()
# Adding stream elements to ADWIN and verifying if drift occurred
for i in range(len(close)):
    adwin.add_element(close[i][0])
    if adwin.detected_change():
        print('Change detected in data: ' + str(close[i][0]) + ' - at index: ' + str(i))

Change detected in data: 284.6 - at index: 127
Change detected in data: 266.1 - at index: 223
Change detected in data: 265.6 - at index: 255
Change detected in data: 268.4 - at index: 287
Change detected in data: 267.4 - at index: 351
Change detected in data: 275.8 - at index: 415
Change detected in data: 284.0 - at index: 447
Change detected in data: 276.3 - at index: 479
Change detected in data: 308.6 - at index: 575
Change detected in data: 320.5 - at index: 607
Change detected in data: 302.4 - at index: 639
Change detected in data: 320.4 - at index: 671
Change detected in data: 369.1 - at index: 767
Change detected in data: 336.2 - at index: 799
Change detected in data: 342.6 - at index: 831
Change detected in data: 382.9 - at index: 927
Change detected in data: 411.3 - at index: 991
Change detected in data: 410.7 - at index: 1023
Change detected in data: 417.1 - at index: 1055
Change detected in data: 393.0 - at index: 1119
Change detected in data: 437.3 - at index: 1215
Change detected in data: 429.2 - at index: 1247
Change detected in data: 428.4 - at index: 1279
Change detected in data: 416.9 - at index: 1343
Change detected in data: 477.7 - at index: 1439
Change detected in data: 492.9 - at index: 1471
Change detected in data: 550.1 - at index: 1503
Change detected in data: 563.9 - at index: 1535
Change detected in data: 600.1 - at index: 1567
Change detected in data: 649.0 - at index: 1599
Change detected in data: 629.5 - at index: 1631
Change detected in data: 634.2 - at index: 1663
Change detected in data: 639.2 - at index: 1791
Change detected in data: 688.3 - at index: 1823
Change detected in data: 675.1 - at index: 1855
Change detected in data: 762.3 - at index: 1951
Change detected in data: 789.1 - at index: 1983
Change detected in data: 880.5 - at index: 2015
Change detected in data: 988.5 - at index: 2047
Change detected in data: 917.6 - at index: 2079
Change detected in data: 808.2 - at index: 2175
Change detected in data: 770.5 - at index: 2239
Change detected in data: 850.1 - at index: 2271
Change detected in data: 906.6 - at index: 2335
Change detected in data: 954.7 - at index: 2367
Change detected in data: 997.1 - at index: 2431
Change detected in data: 1056.4 - at index: 2463
Change detected in data: 1120.9 - at index: 2495
Change detected in data: 1084.5 - at index: 2527
Change detected in data: 1105.4 - at index: 2559
Change detected in data: 1234.4 - at index: 2623
Change detected in data: 1183.9 - at index: 2655
Change detected in data: 1357.6 - at index: 2719
Change detected in data: 1386.2 - at index: 2751
Change detected in data: 1340.3 - at index: 2783
Change detected in data: 1416.1 - at index: 2815
Change detected in data: 1515.3 - at index: 2847
Change detected in data: 1542.0 - at index: 2879
Change detected in data: 1659.0 - at index: 2911
Change detected in data: 1809.1 - at index: 2943
Change detected in data: 1765.1 - at index: 2975
Change detected in data: 1748.4 - at index: 3039
Change detected in data: 1620.2 - at index: 3167
Change detected in data: 1726.0 - at index: 3231
Change detected in data: 1660.7 - at index: 3263
Change detected in data: 1600.9 - at index: 3327
Change detected in data: 1396.2 - at index: 3359
Change detected in data: 1255.7 - at index: 3391
Change detected in data: 1360.9 - at index: 3423
Change detected in data: 1327.0 - at index: 3455
Change detected in data: 1289.8 - at index: 3551
Change detected in data: 1295.8 - at index: 3615
Change detected in data: 1322.6 - at index: 3647
Change detected in data: 1222.0 - at index: 3711
Change detected in data: 1142.6 - at index: 3743
Change detected in data: 1179.8 - at index: 3775
Change detected in data: 1193.2 - at index: 3871
Change detected in data: 1119.0 - at index: 3967
Change detected in data: 1061.6 - at index: 4031
Change detected in data: 1116.4 - at index: 4063
Change detected in data: 1290.5 - at index: 4127
Change detected in data: 1288.1 - at index: 4159
Change detected in data: 1266.6 - at index: 4255
Change detected in data: 1192.5 - at index: 4319
Change detected in data: 1268.9 - at index: 4415
Change detected in data: 1253.1 - at index: 4543
Change detected in data: 1361.4 - at index: 4575
Change detected in data: 1322.8 - at index: 4639
Change detected in data: 1224.6 - at index: 4767
Change detected in data: 1242.6 - at index: 4799
Change detected in data: 1283.4 - at index: 4831
Change detected in data: 1273.2 - at index: 4895
Change detected in data: 1342.7 - at index: 4927
Change detected in data: 1426.9 - at index: 4959
Change detected in data: 1560.4 - at index: 4991
Change detected in data: 1488.2 - at index: 5023
Change detected in data: 1478.2 - at index: 5055
Change detected in data: 1711.2 - at index: 5151
Change detected in data: 1704.8 - at index: 5183
Change detected in data: 1810.0 - at index: 5215
Change detected in data: 1978.9 - at index: 5247
Change detected in data: 1908.9 - at index: 5279
Change detected in data: 1733.6 - at index: 5375
Change detected in data: 1905.0 - at index: 5439
Change detected in data: 1812.2 - at index: 5503
Change detected in data: 1794.7 - at index: 5535
Change detected in data: 1857.3 - at index: 5695
Change detected in data: 1768.8 - at index: 5823
Change detected in data: 1898.8 - at index: 5855
Change detected in data: 1845.4 - at index: 5887
Change detected in data: 2007.0 - at index: 5919
Change detected in data: 1978.0 - at index: 5951
Change detected in data: 1980.4 - at index: 5983